FROM ubuntu:latest 

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    wget \
    && wget http://www.fftw.org/fftw-3.3.10.tar.gz \
    && tar -xzf fftw-3.3.10.tar.gz \
    && cd fftw-3.3.10 \
    && ./configure --enable-shared \
    && make \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf fftw-3.3.10 fftw-3.3.10.tar.gz \
    && apt-get clean

    # Set up the working directory for SPANDAK
WORKDIR /SPANDAK

CMD ["bash"]